/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import model.Car;
import model.Carlist;

/**
 *
 * @author anshitaverma
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Carlist details;
    
    public CreateJPanel(Carlist details) {
        initComponents();
        this.details=details;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtCompany = new javax.swing.JTextField();
        txtManufacturingYr = new javax.swing.JTextField();
        txtseats = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        chkavailable = new javax.swing.JCheckBox();
        chkRegistered = new javax.swing.JCheckBox();
        chkCertificate = new javax.swing.JCheckBox();

        jLabel9.setText("jLabel9");

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        jLabel1.setText("Uber Cars");

        jLabel2.setText("Company");

        jLabel3.setText("Available");

        jLabel4.setText("Manufacturing Year");

        jLabel5.setText("Number of Seats");

        jLabel6.setText("Serial Number");

        jLabel7.setText("Model Number");

        jLabel8.setText("Registered ");

        jLabel10.setText("Certificate Expired");

        jLabel11.setText("City");

        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });

        chkavailable.setText("YES");

        chkRegistered.setText("YES");

        chkCertificate.setText("YES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkavailable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCompany)
                                        .addComponent(txtManufacturingYr)
                                        .addComponent(txtseats)
                                        .addComponent(txtSerialNo)
                                        .addComponent(txtModelNo)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkRegistered)
                                    .addComponent(chkCertificate)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(btnSave)))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chkavailable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtManufacturingYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chkRegistered))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(chkCertificate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnSave)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
//    private boolean isValid(){
//     return
//    }
   
    private boolean isValidCompanyName(String name){
        return (name==null)||(name.equals(""));
    }
    private boolean isValidYear(String year){
    return (year==null)||!(year.matches("([0][1-9]|1[0-2])/([0][1-9]|[1][0-9]|[2][0-9]|[3][0-1])/[0-9]{4}"));
    }
    
    private boolean isValidSeats(Integer seats){
        return (seats==null)||!(seats.toString().matches("\\d"));
    }
    
    private boolean isValidSerial(Integer serial){
        return (serial==null)||!(serial.toString().matches("\\d"));
    }
    private boolean isValidModel(String model){
        return (model==null)||model.equals("")||!(model.matches("[A-Za-z0-9]+"));
    }
    
    private boolean isValidCity(String city){
        return (city==null)||city.equals("")||!(city.matches("[A-Za-z]+( [A-Za-z]+)?"));
    }
    
    private void clear(){
         txtCompany.setText("");
         chkavailable.setSelected(false);
         txtManufacturingYr.setText("");
         txtseats.setText("");
         txtSerialNo.setText("");
         txtModelNo.setText("");
         chkRegistered.setSelected(false);
         chkCertificate.setSelected(false);
         txtCity.setText("");
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
         
         String company=txtCompany.getText();
         boolean available= chkavailable.isSelected();
         String mnyear=txtManufacturingYr.getText();
         String modelNo=txtModelNo.getText();
         boolean register=chkRegistered.isSelected();
         boolean certificate=chkCertificate.isSelected();
         String city=txtCity.getText();
         int seats = 0;
         int serialNo = 0;

         
         if(!(txtseats.getText()==null||txtseats.getText()==""||txtseats.getText().isBlank()||txtseats.getText().isEmpty()))
         {
              seats=Integer.parseInt(txtseats.getText());
           }
         if(!(txtSerialNo.getText()==null||txtSerialNo.getText()==""||txtSerialNo.getText().isBlank()||txtSerialNo.getText().isEmpty()))
         {
            serialNo=Integer.parseInt(txtSerialNo.getText());
         }
         
         if(details.getSerialNumbers().contains(serialNo))
         {
             JOptionPane.showMessageDialog(this, "Serial Number Already Exist. Enter Unique Serial Number");
             clear();
         }
         else if(isValidCompanyName(company))
         {
            JOptionPane.showMessageDialog(this, "Enter Valid Company Name ");
            clear();
         }
         else if(isValidYear(mnyear))
         {
            JOptionPane.showMessageDialog(this, "Enter Valid Manufaturing Date, Date should be in mm/dd/yyyy format");
            clear();
         }
         else if(isValidModel(modelNo))
         {
            JOptionPane.showMessageDialog(this, "Enter Valid Model Number");
            clear();
         }
         else if(isValidCity(city))
         {
            JOptionPane.showMessageDialog(this, "Enter Valid City");
            clear();
         }
        
         else
         {
                Car cr = details.addNewCars();
                details.addSerialNumber(serialNo);
                
                cr.setCompany(company);
                cr.setAvailable(available);
                cr.setManufacturedYear(mnyear);
                cr.setNumberOfSeat(seats);
                cr.setSerialNumber(serialNo);
                cr.setModelNumber(modelNo);
                cr.setRegUber(register);
                cr.setMtCertificate(certificate);
                cr.setCity(city);
                details.setTimeStamp(new Date());
                
                JOptionPane.showMessageDialog(this, "Car details are added");
                clear();
         }
        
                     
         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkCertificate;
    private javax.swing.JCheckBox chkRegistered;
    private javax.swing.JCheckBox chkavailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtManufacturingYr;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtseats;
    // End of variables declaration//GEN-END:variables
}
