/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import static java.time.LocalDate.now;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.Carlist;

/**
 *
 * @author anshitaverma
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    Carlist details;
    public ViewJPanel(Carlist details) {
        initComponents();
        this.details=details;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        txtManufacturingYr = new javax.swing.JTextField();
        txtseats = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        chkavailable = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkRegistered = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        chkCertificate = new javax.swing.JCheckBox();
        btnUpdate = new javax.swing.JButton();
        lblTimestamp = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Luminari", 0, 24)); // NOI18N
        jLabel1.setText("Uber Cars");

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Company", "Availabilty", "Manufacturing Year", "Number Of Seats", "Serial Number", "Model Numberl", "Registerd with Uber ", "Certificate ", "Operation City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblView);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel11.setText("City");

        txtCompany.setEditable(false);

        txtManufacturingYr.setEditable(false);

        txtseats.setEditable(false);

        txtSerialNo.setEditable(false);

        txtModelNo.setEditable(false);

        txtCity.setEditable(false);

        chkavailable.setText("YES");

        jLabel2.setText("Company");

        jLabel3.setText("Available");

        jLabel4.setText("Manufacturing Year");

        jLabel5.setText("Number of Seats");

        jLabel6.setText("Serial Number");

        jLabel7.setText("Model Number");

        jLabel8.setText("Registered ");

        chkRegistered.setText("YES");

        jLabel10.setText("Certificate Expired");

        chkCertificate.setText("YES");

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel9.setText("Last Updated Records:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(12, 12, 12)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkavailable)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCompany)
                                .addComponent(txtManufacturingYr)
                                .addComponent(txtseats)
                                .addComponent(txtSerialNo)
                                .addComponent(txtModelNo)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkRegistered)
                            .addComponent(chkCertificate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chkavailable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtManufacturingYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chkRegistered))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(chkCertificate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex= tblView.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        Car selectedCars=(Car) model.getValueAt(selectedRowIndex, 0);
        
        details.deleteCars(selectedCars);
        
        JOptionPane.showMessageDialog(this, "Car Details deleted");
        
        populateTable();
        details.setTimeStamp(new Date());
        lblTimestamp.setText(details.getTimeStamp().toString());
        
        txtCompany.setText("");
        chkavailable.setSelected(false);
        txtManufacturingYr.setText("");
        txtseats.setText("");
        txtSerialNo.setText("");
        txtModelNo.setText("");
        chkRegistered.setSelected(false);
        chkCertificate.setSelected(false);
        txtCity.setText("");
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex= tblView.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to View.");
            return;
        }
        
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        Car selectedCars=(Car) model.getValueAt(selectedRowIndex, 0);
       
        
        txtCompany.setText(selectedCars.getCompany());
        chkavailable.setSelected(selectedCars.isAvailable());
        txtManufacturingYr.setText(selectedCars.getManufacturedYear());
        txtseats.setText(String.valueOf(selectedCars.getNumberOfSeat()));
        txtSerialNo.setText(String.valueOf(selectedCars.getSerialNumber()));
        txtModelNo.setText(selectedCars.getModelNumber());
        chkRegistered.setSelected(selectedCars.isRegUber());
        chkCertificate.setSelected(selectedCars.isMtCertificate());
        txtCity.setText(selectedCars.getCity());
        
        txtCompany.setEditable(true);
        //chkavailable.setSelected(false);
        txtManufacturingYr.setEditable(true);
        txtseats.setEditable(true);
        txtSerialNo.setEditable(false);
        txtModelNo.setEditable(true);
//        chkRegistered.setSelected(selectedCars.isRegUber());
//        chkCertificate.setSelected(selectedCars.isMtCertificate());
        txtCity.setEditable(true);
        
        btnUpdate.setEnabled(true);
       
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       
        
        int selectedRowIndex= tblView.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row and click View to Update.");
            return;
        }
        
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        Car selectedCar=(Car) model.getValueAt(selectedRowIndex, 0);
       
        
         String company=txtCompany.getText();
         boolean available= chkavailable.isSelected();
         String mnyear=txtManufacturingYr.getText();
         String modelNo=txtModelNo.getText();
         boolean register=chkRegistered.isSelected();
         boolean certificate=chkCertificate.isSelected();
         String city=txtCity.getText();
         int seats = 0;
        

         
         if(!(txtseats.getText()==null||txtseats.getText()==""||txtseats.getText().isBlank()||txtseats.getText().isEmpty()))
         {
              seats=Integer.parseInt(txtseats.getText());
           }
        
        selectedCar.setCompany(company);
        selectedCar.setCity(city);
        selectedCar.setManufacturedYear(mnyear);
        selectedCar.setModelNumber(modelNo);
        selectedCar.setNumberOfSeat(seats);
        selectedCar.setMtCertificate(certificate);
        selectedCar.setRegUber(register);
        
        details.updateCar(selectedCar);
        
        JOptionPane.showMessageDialog(this, "Row Updated, Please Reload page to see changes.");
        
        details.setTimeStamp(new Date());
        lblTimestamp.setText(details.getTimeStamp().toString());
        
         txtCompany.setText("");
         chkavailable.setSelected(false);
         txtManufacturingYr.setText("");
         txtseats.setText("");
         txtSerialNo.setText("");
         txtModelNo.setText("");
         chkRegistered.setSelected(false);
         chkCertificate.setSelected(false);
         txtCity.setText("");
         
         txtCompany.setEditable(false);
       
         txtManufacturingYr.setEditable(false);
         txtseats.setEditable(false);
         txtSerialNo.setEditable(false);
         txtModelNo.setEditable(false);
        
         txtCity.setEditable(false);
         
          btnUpdate.setEnabled(false);
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chkCertificate;
    private javax.swing.JCheckBox chkRegistered;
    private javax.swing.JCheckBox chkavailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTimestamp;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtManufacturingYr;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtseats;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        model.setRowCount(0);
        for(Car cr:details.getDetails()){
            Object[] row=new Object[10];
            row[0]= cr;
            row[1]=cr.isAvailable();
            row[2]=cr.getManufacturedYear();
            row[3]=cr.getNumberOfSeat();
            row[4]=cr.getSerialNumber();
            row[5]=cr.getModelNumber();
            if(cr.isRegUber()){
            row[6]= "YES";
                    }
            else{
                row[6]="NO";
            }
            if(cr.isMtCertificate()){
            row[7]= "EXPIRED";
                    }
            else{
                row[7]="VALID";
            }
            row[8]=cr.getCity();
            model.addRow(row);
        }
       
        if(details.getTimeStamp() != null)
        {
           lblTimestamp.setText(details.getTimeStamp().toString());
        }
    }
}
